# Generated by Django 4.2.20 on 2025-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_todo_todoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
